### ISSUE TITLE
allow "$" char in names 

### ISSUE THREAD

**Issue by chandu0101** [facebook/graphql#102]
scala.js emits constructor names with` $` chars , react-relay takes constructor name as mutation query name and resulting in failed transactions :(. i reported this in scala.js channel

>@sjrd is it possible to remove $ in generated constructor/class names for scalajsdefined classes ? graphql supported names set /[_A-Za-z][_0-9A-Za-z]*/, with current constructor names graphql api requests are failing in fastOptJS mode

response from scala.js author : 

>@chandu0101 No it is not possible. graphql most be fixed to support all valid Javascript identifiers.

so is it possible to accept names that comply with javascript identifiers ?

**Comment by xsistens** [comment]
:+1:

**Comment by leebyron** [comment]
I don't think we will consider doing this because GraphQL wishes to be compatible with many languages and so have designed valid identifiers to be that which is common across many popular languages. Unfortunately characters like `$`, `!` and `?` which are legal identifier characters in some languages are not in other popular languages.

It looks like handling this at the relay layer to ensure that any code that is generating GraphQL identifiers from JavaScript identifiers properly handles the conversion is the correct decision.
