### ISSUE TITLE
Consider using data structures rather than a grammar to define the language

### ISSUE THREAD

**Issue by kylewilt** [facebook/graphql#115]
This just feels like SQL all over again where you have to do string concatenation rather than building real data structures to talk to a server. Using a data format (or formats) would be far friendlier and less error prone to implement in the long run. For example I was working with a .NET implementation recently that didn't quite have the grammar implemented correctly and allowed for strings to be provided to the server that didn't have correctly closing curly braces. Data structure formats basically prevent this kind of thing and many other easy to create problems with custom grammars.

If the syntax could be defined in terms of data structures rather than a custom grammar it would make implementations on both client and server simpler and more flexible. Versioning the spec would likely also be simpler. Testing is definitely simpler on both ends as well since you can use the native data structures of your environment with a little conversion to json, or EDN, or whatever you want for the wire format(s).

**Comment by fabiosussetto** [comment]
@kylewilt just out of curiosity, are you talking about implementing queries like in mongodb or elasticsearch, e.g.
```
db.inventory.find(
   {
     type: 'food',
     $or: [ { qty: { $gt: 100 } }, { price: { $lt: 9.95 } } ]
   }
)
```
instead of using a SQL-like syntax?

**Comment by kylewilt** [comment]
Yes that's the basic idea, of course that's a language specific implementation in your example. Ideally GraphQL would be defined in terms of pure conceptual data structures with basic rules/expectations so that any language can fairly easily implement the language without the string concatenation noise. You can always define a string representation over top of data structures but going the other direction is unpleasant. I can see a future world of "GraphQL Mappers" that turn your nice friendly language constructs into GraphQL text. Not really the world I'd prefer personally.

**Comment by leebyron** [comment]
We did in fact consider this and decided that the legibility of the query language was one of the critical factors we wanted to include. We were not able to come up with a JSON-specific representation that both covered all the cases and was easy to write and read. If someone wants to produce a library which defines such a thing and converts to and from GraphQL, I think that would be a perfectly good community project, but for now GraphQL will continue to maintain its language.

**Comment by leebyron** [comment]
Another important consideration is that GraphQL is defined to be a common request language regardless of frontend or backend languages involved. Since different languages have different representations of data structures, we still must agree upon a serialization format which can represent these concepts across most environments. JSON is probably the go-to for this sort of thing, but JSON feels pretty limiting for this task.

EDN is an interesting alternative because it is far more flexible than JSON, and [datascript](https://github.com/tonsky/datascript) is a pretty great example of how EDN can be used to define this kind of macro language / datastructure. Taking a dependency on EDN is probably not the right decision for GraphQL, but we would encourage experimentation with EDN-macro style GraphQL-like systems.
