### ISSUE TITLE
Offline, caching, service workers

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/graphql#124]
_It was bound to come up. :boom:_

What's the outlook from the GraphQL team on this? Whenever I've seen it brought up to the Falcor team, they say it's not their focus. 

With the capabilities provided by Service Workers, and newer, smarter caching techniques emerging, is it out of the realm of possibilities to consider GraphQL queries/results being cached offline?

**Comment by sjatkins** [comment]
Wouldn't you want caching on whatever backend more than in the frontend that I understand is the primary focus of this project?

**Comment by leebyron** [comment]
I'm no expert on service workers, but I'm not sure GraphQL needs to be anything other than agnostic towards it as a technology? I believe you should be able to run your GraphQL queries from a service worker if you wish.

**Comment by leebyron** [comment]
I should mention though that a pure HTTP cache is acceptable but often underwhelming when paired with GraphQL, for similar reasons for why directly caching the results of SQL queries are underwhelming. 

A great GraphQL cache is aware of the relevant schema and can ensure new information gleaned from one query can benefit the cached results of other queries.

Since a great example of a GraphQL client cache is [Relay](https://github.com/facebook/relay), you might consider furthering this conversation there. I know offline support is something they've been thinking about within future plans.

**Comment by kevinSuttle** [comment]
Very cool. Thanks @leebyron. Will approach the Relay team.
