### ISSUE TITLE
[Docs] Should this section in Relay's docs be moved to GraphQL.org?

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/graphql#131]
https://facebook.github.io/relay/docs/graphql-connections.html#content

**Comment by leebyron** [comment]
Perhaps we'll consider this as we expand documentation to include a "best practices" section. Right now Relay is the only tool which requires connections to be modeled in this way, which is why those documentation details are in a Relay specific place. But we think connections are a good idea in general that many GraphQL backends could take advantage of.

**Comment by alloy** [comment]
@leebyron I don’t know if this is my unique experience, but too often I end up having to explain to newcomers that these are not _just_ for Relay, but instead a convention that’s indeed a good idea in general.

While I personally love Relay, the connection to Relay (no pun intended) really seems to ruffle people’s feathers in such a way that they actively decide to _not_ use connections, without apparently understanding the full benefits. Instead what I usually hear is a lament about having to do ‘more’ work _for_ Relay when creating their schemas.

While I understand that the GraphQL spec may not be the right place to describe conventions, I would _really_ like to see such convention specs be detached from Relay and where possible move closer to where the GraphQL spec lives.

(The same applies to the Global Object Identification specification btw.)
