### ISSUE TITLE
How to chain multiple operations

### ISSUE THREAD

**Issue by mkawia** [facebook/graphql#138]
I keep getting "Must provide operation name if query contains multiple operations" error even if named the operations . 
example
  query a{
        getSomething(key:"asd"){
           key
        }
    }

mutation m {
  createSomethingElse(name:"900"){
    name
  }
}

I've named the operations ,I have even tried similar query on http://graphql-swapi.parseapp.com/  , what am I missing ,is this not supported? Please help.

Thanks

**Comment by dschafer** [comment]
From http://facebook.github.io/graphql/#sec-Language.Query-Document

> If a document contains only one operation, that operation may be unnamed or represented in the shorthand form, which omits both the query keyword and operation name. Otherwise, if a GraphQL query document contains multiple operations, each operation must be named. When submitting a query document with multiple operations to a GraphQL service, the name of the desired operation to be executed must also be provided.

So you've named both of your operations, but now you need to specify which one you want to run; I don't believe Graphiql supports this (it's a relatively uncommon operation), but the `graphql` top level function in https://github.com/graphql/graphql-js does.

If you wanted to run both, you could either issue two requests, or you could alter the payload of the mutation to allow for this; for example, by ensuring the return value of `createSomethingElse` includes a pointer to the query root, allowing you to then `getSomething`.

It's also reasonable to build a batch API for GraphQL, that would accept this document and ask it to run query `a` and mutation `m`. You might have some issues with ordering in that case (which runs first?), which is why the approach above (embedding the query root in the mutation response) is appealing; the spec makes it clear what the ordering will be there, with an example in http://facebook.github.io/graphql/#sec-Serial-execution.

Hope this helps!

**Comment by mkawia** [comment]
Altering the payload for the mutations makes a lot more sense than what I was going for. Thanks and thanks for graphql.
