### ISSUE TITLE
Inline introspection

### ISSUE THREAD

**Issue by freiksenet** [facebook/graphql#16]
Spec defines `__typename` as a way to get 'inline' introspection for any field. I was under impression that in previous versions of the GraphQL one could get the whole type definition inline with `__type__` (which, I guess, would be `__type` nowadays). I think it was very handy, is there any particular reason why it was removed?

**Comment by leebyron** [comment]
Good eye, our original version of GraphQL exposed `__type` which was the whole type object, the same as what you would get when doing full schema introspection. We started this way for the same reasons you point out, we thought it was going to be really handy.

Well, it turns out we were wrong about that. After three years of development, evolution, and tool building, there was never a single case of someone using `__type` for anything other than `__type { name }` - the core value of this is determining what type you're dealing with at runtime when the field is an abstract type (interface or union) for example:

```
{
  node(id: 123456789) {
    __typename
    ... on User { name, friendCount }
    ... on Page { name, likerCount }
  }
}
```

We have no idea what kind of node `12346789` is, and we're asking for different fields depending on the type, but `__typename` gives us a tag to use when parsing the response should we want to populate strong type client models.

It turned out that this isn't just the common case, but it was basically the only case people were using `__type` for, and there was demand from the tool builders (who are making parsers, etc) to simplify this case.

**Comment by freiksenet** [comment]
Thanks! I trust your experience on that.
