### ISSUE TITLE
Does spec allow for List of Lists?

### ISSUE THREAD

**Issue by danielkwinsor** [facebook/graphql#169]
For the Non-Null wrapper section, there is a subsection [sec-Non-Null-type-validation](http://facebook.github.io/graphql/#sec-Non-Null-type-validation)

However, for the [List wrapper section](http://facebook.github.io/graphql/#sec-Lists), some of the info is scattered or not clear.
For instance, the [sec-Types section](http://facebook.github.io/graphql/#sec-Types) could be interpreted either as allowing List of Lists, or not allowing it.

On the other hand, given a List of Lists object, I'm not even sure on the query syntax -- it seems impossible.

**Comment by helfer** [comment]
The answer is yes. The reference implementation implements it, and the list wrapper section that you reference says that `ofType` can be any, which includes the List type, so lists of lists are possible.

In the query you only need a selection set if the wrapped type is not a scalar. The fact that the type is wrapped in a list doesn't matter at all from the query's perspective. In some ways that could be considered a weak spot in the GraphQL spec, because the query doesn't show you whether you're getting back a list of something or just one object/value.

**Comment by danielkwinsor** [comment]
Thanks @helfer, that definitely seems to be the case, and 4.2.2.9 is quite clear!
