### ISSUE TITLE
merge query and mutation syntax

### ISSUE THREAD

**Issue by yavuzmester** [facebook/graphql#183]
Why not merge query and mutation syntax, so that we can mutate like below?

{
  latestPost {
    title = "New Title",
    author {
        name = "New Name"
   }
  }
}

**Comment by kaqqao** [comment]
How would you tell the difference between a query and a mutation of the same name?

**Comment by yavuzmester** [comment]
In the queries equals sign "=" will not be used.

**Comment by leebyron** [comment]
This would be problematic for a number of reasons:

* It would be unclear which fields could be written in this manner.
* This would field to represent not just a method of producing a value (`resolve`) but would also require them to present a way of writing a value, which in many cases is simply not possible.
* Write-only fields become more difficult to represent.
* Required fields for a mutation are more difficult to represent.
* This implies that there are many independent single-value mutations, but typically you want to describe a mutation as an atomic operation. Especially since those atomic operations tend to have other side-effects as well (writing to your logging system, sending notifications, etc)
* Mutations themselves typically result in a value which at least describes if the mutation was successful and may also return related values so you can query the result of the mutation. This is harder to do when not represented as an atomic operation.

Lastly, it's a bit misleading to say this is a merging of syntax, as actually the syntax for queries and mutations is already "merged" or identical. There is no additional syntax to a mutation in GraphQL other than using the `mutation` keyword rather than `query` keyword, but that has less to do with syntax and more to do with creating a well typed schema such that all mutations can be statically describable and thus easier to understand what's possible and determine if a mutation is valid before sending it.
