### ISSUE TITLE
subselection on GraphQLOBjectType should be optional.

### ISSUE THREAD

**Issue by hepin1989** [facebook/graphql#195]
If someone just want to get all the data,then there is much cumbersome to write done all the field.
a better way I think is make the sub selection optional,if there are sub selections,we return an subset of the original data,otherwise,we return a full set.

**Comment by dylanahsmith** [comment]
That would result in a lot of problems:
* More data would be returned than necessary
* It would be hard to detect when clients are no longer using a deprecated field
* Would it recursively return all data for object type fields?  If so, then that could cause infinite recursion if there are circular reference.

**Comment by hepin1989** [comment]
@dylanahsmith Anyway,I have implemented in that way,and circular reference could be fixed if you use the right configuration.

**Comment by leebyron** [comment]
GraphQL explicitly does not allow this because of backwards compatibility.

An important characteristic of a query is that it completely describes the data being requested. Critically, that allows the freedom to evolve a schema over time, including adding new fields to existing types, with the knowledge that all existing queries will be unaffected.

This is very related to the old wisdom to never use `SELECT *` in your production SQL queries.
