### ISSUE TITLE
Can a root operation type be an interface?

### ISSUE THREAD

**Issue by dminkovsky** [facebook/graphql#198]
The answer, judging from the [JS]
(https://github.com/graphql/graphql-js/blob/v0.6.2/src/execution/execute.js#L256) and [Java](https://github.com/graphql-java/graphql-java/blob/v2.0.0/src/main/java/graphql/execution/Execution.java#L36) implementations is: No.

But—and I am sorry if I missed this in the spec—I don't see this stipulated anywhere. In 6.4 it does say: 

> The type system, as described in the “Type System” part of the spec, must provide a “Query Root” and a “Mutation Root” object.

but is that a specific reference to the Output Object type?

And I wonder: why can't we use interfaces (or unions)? It is simpler to just use object types as roots. But it wouldn't be that much more complicated to resolve a root interface type against the root input, just as you do when completing non-root values.

Either way, maybe add this to the spec if I didn't miss it? Is it fine the way it is?

**Comment by dschafer** [comment]
> but is that a specific reference to the Output Object type?

Yeah, the query root and mutation root need to be output object types in the http://facebook.github.io/graphql/#sec-Objects sense. We should probably clarify the spec to make that more explicit in that section.

> And I wonder: why can't we use interfaces (or unions)? It is simpler to just use object types as roots. But it wouldn't be that much more complicated to resolve a root interface type against the root input, just as you do when completing non-root values.

So fields **on the root object** can return interfaces and unions using inputs passed to them (the example schema in graphql-js does this a few times). At the very top level, for the root object itself, the only thing we know is whether it was a query or mutation, and that's the only thing the root type should depend on (hence queryRoot vs. mutationRoot). Because we would need additional context to resolve an interface/union down to an object, the root type must be an object type.

Hope this helps!

**Comment by dminkovsky** [comment]
Before I made the following comment, I'd like to stress that I'm not at all advocating interfaces/unions be allowed on the root. I am writing some GraphQL-related code and was simply not sure whether this was allowed. I, personally, prefer it to be simple the way it is.

But regarding:

> Because we would need additional context to resolve an interface/union down to an object, the root type must be an object type.

I'm not sure I understand we don't have all the context we need. Every root operation receives a "root value". 

In the Java implementation it's the  `Object root` param

```
public ExecutionResult execute(GraphQLSchema graphQLSchema, Object root, Document document, String operationName, Map<String, Object> args)
```

In the reference JS implementation it's the `rootValue?: mixed` param

```
export function execute(
  schema: GraphQLSchema,
  documentAST: Document,
  rootValue?: mixed,
  contextValue?: mixed,
  variableValues?: ?{[key: string]: mixed},
  operationName?: ?string
)
```

When executing the root type, if the type is abstract, this root value can be used to determine the type. That's all you need to call determine the type:

```
  const runtimeType = returnType.resolveType ?
    returnType.resolveType(result, exeContext.contextValue, info) :
    defaultResolveTypeFn(result, exeContext.contextValue, info, returnType);
```

as found in [`completeAbstractValue()`](https://github.com/graphql/graphql-js/blob/v0.6.2/src/execution/execute.js#L889).

**Comment by dminkovsky** [comment]
But yes, that does help. Thank you for the confirmation!

**Comment by dschafer** [comment]
> I'm not sure I understand we don't have all the context we need. Every root operation receives a "root value".

Ah, that's a good point! Yeah, it could potentially make sense for the root value to be used to resolve an interface or union; I could imagine a case where the schema provides two implementations of the root, one that applies when the user is an admin and the other that applies when the user isn't, and then uses a root value based on auth credentials to determine which one it is. That would be a little bit odd since I don't think I've seen the root value vary like that before (and I don't think I would recommend it), but it's entirely plausible.

This definitely helped clarify my thinking on this, thanks! I'm inclined to agree with you and stick with the simplicity, since we don't have a concrete compelling use case for root Interface/Union, but if one came up it might be worth taking another look at this.

**Comment by dminkovsky** [comment]
> I could imagine a case where the schema provides two implementations of the root, one that applies when the user is an admin and the other that applies when the user isn't, and then uses a root value based on auth credentials to determine which one it is.

Wow—funny you mentioned that as an example. This would actually be an interesting way to solve that exact "problem" (more like an inelegance or annoyance) I've been facing: I've tried to figure out how to have difference schemas based on user roles, but didn't get very far because because `babel-relay-plugin` requires one concrete schema that it works against. So instead everyone has the same schema but relies on access control. So, maybe something to think about.

Thanks again!
