### ISSUE TITLE
open up gitter channel?

### ISSUE THREAD

**Issue by hepin1989** [facebook/graphql#210]
gitter is more accessible

**Comment by fcanela** [comment]
If we look for accesibleness (in spite of usability): IRC

**Comment by leebyron** [comment]
There are already quite a few discussion forums available listed on http://graphql.org/community/

**Comment by pdurbin** [comment]
This just came up again at https://gitter.im/gitterHQ/gitter?at=582732efe097df7575a0ec5e

https://github.com/gitterHQ/gitter/issues/1511 is related.

**Comment by leebyron** [comment]
I'm conflicted on this. I understand the desire for those who have preferred chat tools to want to use those tools to discuss live, however there is also the problem of fragmenting the community across these various discussion platforms. We already have this problem today with more slack rooms than core contributors can keep up with in addition to a freenode irc room where the core team is frequently around, but is otherwise often quiet. 

Are more platforms better at the expense of further fragmentation? Or is consolidating community discussion better at the expense of lack of platform choice?

Another way to frame this is, would it be acceptable to have the gitter room open if it was unofficial and had no promise of any segment of the community or maintainers being available via that channel?

**Comment by stubailo** [comment]
Turning that around, would people show up to that room, expecting in-depth discussion and help, and then be disappointed with GraphQL as a technology if they didn't receive it? I think perhaps they would, which will put pressure on GraphQL maintainers and project leaders to spend time there.

**Comment by intellix** [comment]
I think the problem lies with gitter not allowing communities to appreciate it's platform since the gate is outright closed. There are a billion channels on the web for discussing things even where there are likely no maintainers. Googling "graphql forum" brings up loads of results.

I think it sucks that I've registered about 10 Slack accounts (one for each tech) and they don't even have syntax highlighting... but I'll continue doing it to get where I'll find support :)

Perhaps the room could be opened with a MOTD pointing to the Slack channel?

**Comment by pdurbin** [comment]
Maybe https://sameroom.io or similar could be used to bring various chat services like Slack, IRC, and Gitter together for the GraphQL community.

**Comment by Carringguns** [comment]
Sux when ur asked for help and have to make another room ? I disagree and decided to do just that last night. Its called THE DEW DROP INN.  Point taken and will abide men. Thannks for the input.
