### ISSUE TITLE
Question: why does a schema require a query type?

### ISSUE THREAD

**Issue by dminkovsky** [facebook/graphql#211]
The spec states that a schema requires a query type. This, however, has been a minor source of frustration for me. For example:

* Some services do not need query functionality.
* Writing tests for mutation functionality of a GraphQL implementation, there is no query.

In such cases a "dummy" query must be set up in the schema. Does anyone know the reason for this requirement? 

Thank you!

**Comment by leebyron** [comment]
GraphQL is designed first as a data access API. It's not always well suited for RPC style write-only services. The default constraints are set up to reflect this.

Requiring the query type provides a guarantee for tools. You can *always* query a GraphQL API because of the introspection meta fields. Requiring the query type avoids a scenario where an introspection query is run, but the underlying system is unsure of what type to use throughout validation and execution. Avoiding this edge case helps avoid quirks during implementation.

If you are building a write-only GraphQL service, or just writing tests. A simple near-empty query type should work.

**Comment by dminkovsky** [comment]
Thank you for your time! Curiosity: sated.
