### ISSUE TITLE
Section 2.1.9 Names RegExp ambiguous

### ISSUE THREAD

**Issue by NeoPhi** [facebook/graphql#216]
It looks as though the regular expression used to define valid names within GraphQL (https://facebook.github.io/graphql/#sec-Names) is incorrect. In particular it doesn't include anchors or in the text specify that the entire name must match the given regular expression. I would propose that the specification be updated to `/^[_A-Za-z][_0-9A-Za-z]*$/`.

**Comment by rmosolgo** [comment]
I'm used to using `^` as "beginning of line" and `$` as "end of line", is that what they mean in this context? Or are they given another meaning?

**Comment by NeoPhi** [comment]
The issue is that without anchors specified in the RegExp any substring of the name may match. That is:
```
/[_A-Za-z][_0-9A-Za-z]*/.test('type-6-test') => true
/^[_A-Za-z][_0-9A-Za-z]*$/.test('type-6-test') => false
```

**Comment by tendant** [comment]
The name RegExp is used to define the grammar rule of GraphQL. 

I read it in this way: 

The parser will accept the matching part of RegExp. 

For your example, even

/[_A-Za-z][_0-9A-Za-z]*/.test('type-6-test') => true

Parser will only accept "type" as name, remaining parts will be used to match other grammar rules.

If something needs to be changed I would suggest remove '/', instead of add '^' and '$'. 

By remove '/', people will not treat RegExp as RegExp in Javascript. Since '^' and '$' is not part of the name in grammar rule for name, it should not be included in the definition of name.

**Comment by NeoPhi** [comment]
Based on https://facebook.github.io/graphql/#sec-Appendix-Notation-Conventions the need for anchors is not needed as a non matching name would capture as much as needed and the remaining would produce an invalid document since the following characters would be applies to the next rule and fail.
