### ISSUE TITLE
response values for unauthorized resources?

### ISSUE THREAD

**Issue by leemason** [facebook/graphql#241]
Ive scoured the docs and cant find a concrete answer (im guessing null if the right value, but cant be sure).

consider i request all users from the api (this is a relay like query on a connection object, but point stands for anything)

```
query users(first: 10){
    edges{
        cursor
        node{
            id
        }
   }
   totalCount
}
```

If i request this as an admin, all is well. However if i were to request this as less authorative user i may not be able to see all users (definded by the app).

1. should totalCount be a count of ALL users, even ones i can see, or a count of the ones i can
2. edges is a list of cursor/nodes, if i cant view that user, should this item be null, or simply removed from the list
3. cursor while not actual data about the user, is data attached to that specific user, should this be null?
4. if i do send back nulls for each edge, should i add an error to the response, and if yes should it be 1 error per "edge" that fails, or 1 global error that covers all?

**Comment by leebyron** [comment]
Great questions and sorry for letting this issue sit (GH Issues are typically being used to track RFCs)

> should totalCount be a count of ALL users, even ones i can see, or a count of the ones i can

This is totally up to your implementation. Presumably the count of the values you can access would be best, but this may be more expensive than an unfiltered count. For large collections or collections which change size often even knowing an accurate unfiltered count may be cost-prohibitive and you may fall back on a reasonable estimate. I've seen all of the strategies taken for counting lists of things at Facebook.

> edges is a list of cursor/nodes, if i cant view that user, should this item be null, or simply removed from the list

Again this is up to you, but I've personally found that APIs which filter out values that you cannot access are easier to use than those which leave the values in the list but return errors/null for them. This may depend on if the index in the list is important or not (typically its not).

> cursor while not actual data about the user, is data attached to that specific user, should this be null?

Also totally up to you. Presumably if it is semantically important to include the edge but leave the node in the edge null due to access control, then you would still want a cursor. For example, if you load a page of items and the last one happens to have a `null` value, you would still want the cursor to continue pagination.

But again, this is the kind of problem which can make an API more cumbersome to deal with. Filtering out the values from a list you're not allowed to access may simplify things if that is okay.

> if i do send back nulls for each edge, should i add an error to the response, and if yes should it be 1 error per "edge" that fails, or 1 global error that covers all?

Presumably if accessing these edges is each represented by an error then the spec would suggest that one error occurs per errored edge. That would be true regardless of if we're talking about access control or anything else which may produce an error.
