### ISSUE TITLE
how to do data operations in ql?

### ISSUE THREAD

**Issue by lizherui** [facebook/graphql#243]
Grammars like a.b、&|!、+-*/()、sort、filter、map、reduce、join、groupBy in graphql？

**Comment by stubailo** [comment]
GraphQL intentionally does not support these. It's an API query language, which means it's designed to let you call explicitly specified fields with specified arguments. It doesn't include arbitrary logic like SQL does because the server needs to be able to predict what the client could request.

It's very easy to construct an expensive and insecure SQL query using these constructs, which is one reason people don't send SQL queries over the internet as their API. GraphQL is designed for exactly that, so it's intentionally limited.
