### ISSUE TITLE
How to use graphql like graph api?

### ISSUE THREAD

**Issue by kamikaze123** [facebook/graphql#253]
Is it possible to use graphql like graph api? 

Graph API can get friend information by making a request like...

GET https://graph.facebook.com/user-id/friends?access_token=TOKEN

How can get the same information by using graphql? Please teach me the example URL.

**Comment by smolinari** [comment]
https://learngraphql.com/

Scott

**Comment by kamikaze123** [comment]
I opened this issue because no one shared full url or curl command for graphql. There are many sites which explain how to use graphql, but there is no site that teach "how to use graphql like graph api."

------------------------------------------

Full url example:

GET https://graph.facebook.com/user-id/friends?access_token=TOKEN

--------------------------------------------

**Comment by kamikaze123** [comment]
I want to use graphql on  "https://graph.facebook.com." I looked for information, but i could not find...

**Comment by smolinari** [comment]
Facebook's open graph API has nothing directly to do with GraphQL. 

Scott

**Comment by kamikaze123** [comment]
I found a blog post...

http://philippeharewood.com/political-endorsement-is-shown-to-friends-while-endorsement-post-set-to-private/

Researcher Philippe Harewood submitted many security issues about graphql witch used on  "https://graph.facebook.com."

---------------------------------------------------------------------------------------------

If facebook's open graph API has nothing directly to do with GraphQL, Why could researcher use graphql on https://graph.facebook.com??

**Comment by smolinari** [comment]
Interesting. I guess I stand corrected. It looks like Facebook has their Graph API exposed through a GraphQL interface, but it isn't documented anywhere that I could find.  So if you have an access token from Facebook, you can use the Graph API by querying it via GraphQL. 

Still, you need to learn GraphQL. 

And GraphQL is only as insecure as you make it, just like about anything else that is programmed and takes user input.  

Scott

**Comment by calebmer** [comment]
I'm not certain (because I don't work at Facebook), but that looks like their internal version of GraphQL before making it an open source specification. A similar style can be seen in the presentation where they first previewed GraphQL before it was open sourced: https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql

So this repo/community probably can't help you understand the pre open source GraphQL language accessible at the endpoint in the blogpost, only a Facebook engineer could help with that. But I'm not sure they would given it appears that endpoint is for internal use only (because it's not documented), and from what the community has been told Facebook is trying to move away from the pre-open source GraphQL to the specification that can be found in this repo.

**Comment by kamikaze123** [comment]
I wondered how researcher figured out these endpoint.... because there is no document

**Comment by kamikaze123** [comment]
I am going to close this. Maybe I need to look for myself...
