### ISSUE TITLE
Language about double-underscore artifacts could be better organized

### ISSUE THREAD

**Issue by stubailo** [facebook/graphql#258]
In [section 3, Type System](http://facebook.github.io/graphql/#sec-Type-System), the spec says:

> All types and directives defined within a schema must not have a name which begins with "__" (two underscores), as this is used exclusively by GraphQL’s introspection system.

In [4.1.1, Naming conventions](http://facebook.github.io/graphql/#sec-Naming-conventions), the language is:

> Types and fields required by the GraphQL introspection system that are used in the same context as user‐defined types and fields are prefixed with "__" two underscores. This in order to avoid naming collisions with user‐defined GraphQL types. Conversely, GraphQL type system authors must not define any types, fields, arguments, or any other type system artifact with two leading underscores.

I can imagine a situation where someone might read one but not the other, and it seems like 4.1.1 supersedes 3. Personally, it makes sense that restrictions on field names, etc, would go in the section about the Type System and not introspection.

Also, the title of the section contains the word "conventions" which doesn't match with usage of the word "must" in the body of the section.

I'd expect to find information about, for example, camelCasing field names in the section about naming conventions, and I'd probably expect to find all of those things in the "Type System" section rather than introspection.

Of course, you would expect someone to read the entire spec before attempting an implementation but this is one place where the specification could be simplified.

**Comment by leebyron** [comment]
I've landed edits to the section title to be more clear about the the introspection reserved names.

I'm open to suggestions on how you would expect this content to be organized. The goal here was to repeat the same information in context of each place where it is relevant - each section should be cross-supportive rather than conflicting or superseding. This way if a reader only reads section 3 or only reads section 4, they still will find this information.
