### ISSUE TITLE
@include(unless null) ?

### ISSUE THREAD

**Issue by hakimelek** [facebook/graphql#275]
Why not making it easy to return certain fields only if they are not null. Someone already asked this question at Stackoverflow http://stackoverflow.com/questions/36451910/graphql-query-only-include-field-if-not-null

```
query HeroAndFriends {
  hero {
    name @include(unless null)
    friends {
      name
    }
  }
}
```
the response should then look like

```
{
  "data": {
    "hero": {
      "friends": [
        {
          "name": "Luke Skywalker"
        },
        {
          "name": "Han Solo"
        },
        {
          "name": "Leia Organa"
        }
      ]
    }
  }
}
```

instead of

```
{
  "data": {
    "hero": {
      "name": null,
      "friends": [
        {
          "name": "Luke Skywalker"
        },
        {
          "name": "Han Solo"
        },
        {
          "name": "Leia Organa"
        }
      ]
    }
  }
}
```

**Comment by stubailo** [comment]
What's the benefit of doing this?

**Comment by hakimelek** [comment]
It would reduce an extra line of logic from a front end developer perspective, but yes I think I understood your point, it doesn't make too much sense. 

However, I have another use case that required me to create another query and thought that the include would solve the problem (or maybe not). What about if I have an object hero that has name and magic power. Some heros doesn't have magic power and I would like to create one query that returns an array of heros with magic power only. I would like to do something like this

```
query Heros {
  hero {
    name 
    magicPower @include(unless null)
  }
}
```

that returns: 
```
{
  "data": {
    "hero": [
       { 
          "name": "superman",
          "magicPower": "fly"
       }, 
       { 
          "name": "batman",
          "magicPower": "fight"
       }    
    }
  }
}
```

versus: 

```
{
  "data": {
    "hero": [
       { 
          "name": "superman",
          "magicPower": "fly"
       }, 
       { 
          "name": "batman",
          "magicPower": "fight"
       },
       { 
          "name": "normal guy",
          "magicPower": null
       }    
    }
  }
}
```

**Comment by calebmer** [comment]
@hakimelek it would be way easier if you added an argument to your `hero` field instead of a directive 😊

```graphql
query Heros {
  hero(skipNoMagicPowers: true) {
    name 
    magicPower
  }
}
```

**Comment by chrisregnier** [comment]
I've got another valid case for something like this (or maybe an @optional directive)
If you have the following schema
```
type Power {
  id: ID!                    # a Power will ALWAYS have an id
  name: String!              # a Power will ALWAYS have a name
}
type Hero {
  name: String
  magicPower: Power          # should allow null, hero may not have a power
}
```
and the query
```
query {
  hero(heroId: specificHeroId) {
    name
    magicPower {
      id
      name
    }
  }
}
```
Because id and/or name are declared non null, hero MUST have a power since I can't return null for magicPower (even though the type for magicPower should allow null). I understand the need to throw errors in this case because returning null for magicPower would mean either the shape no longer respects the query shape, or you're returning null for the values (which is not allowed based on the type system). 

I think an @include(unless null) or @optional directive would solve this by allowing magicPower to either not be in the result, or allow it to explicitly be null and not match the query shape.
```
query {
  hero(heroId: specificHeroId) {
    name
    magicPower @optional(useNull: true) {
      id
      name
    }
  }
}
```

opinions?

**Comment by nagman** [comment]
Totally agree with chrisregnier.
I'm encountering the same problem.
Is there a way to include a type only if it is not null and in the same time keep the not null ! on the subfields?

**Comment by chrisregnier** [comment]
So I don't know what happened the other night, cause the problem I describe above seems to be working for me now. (I'm assuming I had cached data somewhere, which meant a night of wild goose chasing :( )

In my query above,`magicPower` can be null w/o the `@optional` directive. However, the original request for removing `magicPower` completely from the result if null still stands, although I see less of a need for that case.

**Comment by hnryjms** [comment]
^ for anyone stumbling across this thread, my team experienced the same problem using [Automattic/mongoose](https://github.com/Automattic/mongoose) and GraphQL-JS.

Our issue is that Mongoose returns empty-objects for `null` fields, rather than a falsey value. This makes GQL think the field is set, and then the NonNull field inside that type is improperly defined. Currently the solution below makes things work, but I'm not in love with it. Another option would be for root functions to always return a [`.lean()`](http://mongoosejs.com/docs/api.html#query_Query-lean) or [`toObject()`](http://mongoosejs.com/docs/api.html#document_Document-toObject) value, so this Mongoose functionality is stripped off from `root`.

```js
// ... const MagicPowerType = { ... };

const HeroType = new GraphQLObjectType({
    name: 'Hero',
    fields: {
        name: {
            type: GraphQLString,
        }
        magicPower: {
            type: MagicPowerType,
            resolve: (root) => root.toObject().magicPower, // Prevent Mongoose pseudo-objects for `null` properties
        }
    }
});
```
