### ISSUE TITLE
fully recursive query on a root query

### ISSUE THREAD

**Issue by serle** [facebook/graphql#303]
I have a fairly deep object tree. I want to be able to get all field in the whole object tree as opposed to specify which one I want in a query each time. Is this possible?

**Comment by robzhu** [comment]
First, a fully recursive query from the root would not terminate if there is a mutual reference between two types. Second, your queries will no longer be predictable because the client is not in control of the data the server sends back. If you can mitigate these issues, then you can do what you're describing by executing an introspection query like so: 

```
{
  __schema {
    types {
      name
      fields {
        name
      }
    }
  }
}
```

From this, you can construct the "full" query for each type, and assemble a root query that consists of these fragments.

**Comment by wincent** [comment]
Thanks for the question @serle. I'm going to close this on the assumption that @robzhu's answer has been sufficient.

The other observation I would make is that it would also be possible to create even a mutually recursive query to a fixed depth with the aid of some directives, but I am not aware of any existing tooling to do this so you might have to hand-roll it yourself. It is somewhat of an abuse of directives, so I wouldn't necessarily recommend this.

As a simple example, consider a system with nested comment threads:

```
type Post {
  body: String
  comments: [Comment]
}

type Comment {
  text: String
  comments: [Comment]
}
```

You could abuse directives to write a query like this:

```
query PostQuery {
  post {
    ...CommentsFragment
  }
}

fragments CommentsFragment on Post {
  comments {
    text
    ...CommentsFragment @recurse(depth: 2)
  }
}
```

And have a static build-step that would transform that into:

```
query PostQuery {
  post {
    comments {
      text
      comments {
        text
        comments {
          text
        }
      }
    }
  }
}
```

(or similar).

**Comment by serle** [comment]
Thanks, makes sense. My use case is more from a build and exploration side. We have a fairly deeply nested configuration object and its a pain to construct the query each time. During development I would just like to get the query string for the latest version of the configuration object as we iterate.
