### ISSUE TITLE
Quoted keys

### ISSUE THREAD

**Issue by dtaub** [facebook/graphql#321]
In json, it's possible to name a key pretty much anything by quoting it. 
```javascript
{ "namespace:foo": "bar" }
```

Could something similar be possible in graphql?
```graphql
{
  things {
    "namespace:foo"
  }
}
```

**Comment by robzhu** [comment]
What's the use case you have in mind?

**Comment by stubailo** [comment]
I think the use case is being able to name fields something other than alphanumeric characters, in order to match some other existing convention.

Personally I think having fields be a lowest-common-denominator thing doesn't hurt a lot. Perhaps this is asking for a feature specifically for namespacing?

**Comment by dtaub** [comment]
Namespacing was just an example. It is, as @stubailo wrote, to be able to name fields any valid string in order to match some existing convention.

I don't need it for the use case I thought I did, so at this point it's basically just theoretical for consistency with json. If there's no interest in it then feel free to close this.

**Comment by stubailo** [comment]
I feel like there's a value to having fields be valid identifiers in pretty much every programming language.

**Comment by leebyron** [comment]
This is something that has come up before, but we've decided against in the name of simplicity.
