### ISSUE TITLE
How can I specify "any" type for the field to just respond as is?

### ISSUE THREAD

**Issue by z-ax** [facebook/graphql#329]
As a result from a Query I might get any value, like just pass a result from other API, depending on some conditions.
Is it possible with GraphQL? Didn't find anything like that in docs and examples.

Here are examples of what I mean, neither of those work for `buildSchema()`:
```
type Query {
  hello1: Any,
  hello2: Object
}
```

**Comment by stubailo** [comment]
You can use a custom scalar for this, for example: https://github.com/taion/graphql-type-json

However, use it wisely, because that means you don't get some of the main benefits of GraphQL like getting only the data you asked for. In fact, you should almost never use the "any" or "json" types if you can help it.

**Comment by z-ax** [comment]
Yeah, for sure it's more like an exception. Thanks for the link, will check it out and for now I think it's closed :)
