### ISSUE TITLE
GraphQL versioning, not nullable to nullable

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#338]
At the begining we have schema
```
type User {
  id: ID!
  name: String!
  birthday: String!
}
```
After some time it was decided that birthday is not mandatory for new users, so the schema should change to
```
type User {
  id: ID!
  name: String!
  birthday: String
}
```
This is breaking change. Old clients can crash, they know that this field is not nullable, but we will send null, because we don't have birthday of all users.

How to versioning case like this in GraphQL?

**Comment by wincent** [comment]
As you've noted, it's a breaking change, and there is no way to make the change without it being a breaking change (that's why it is a breaking change). So, your choices in a situation like this are to chose from among the following:

- Not make the change.
- Make the change, and suffer the consequences (breakage of old clients).
- Make a different change instead.

That second one (making the change anyway) may end up being viable under some circumstances, such as:

- The code never shipped to end-users.
- The count of users on the old client, and specifically the subset that uses features that rely on this data, may be below a certain business-defined threshold that make the breakage acceptable.
- You may have client-side exception handling logic that makes failure to render the related subset of the UI acceptable, according to some business-specific parameters.

The third one (making a different change), could be something like *adding* a new field (eg. `dob`, or "date of birth", that is non-null), and shipping down a non-null (eg. empty string) value for `birthday` if the birthdate is missing. Once again, this depends on product specifics (will your client do a reasonable thing if supplied an empty date string? Do you have date-parsing code that is going to throw an exception and does your client handle it? etc).

This is why it is generally easier to make things nullable by default, because moving things towards non-null is a non-breaking change. Note: *easier*, but not necessarily *better*; an almost-everything-nullable schema is not so pleasant to work with on the client side.

The difficulty here also makes it clear why it is desirable to let schema additions "bake" for an adequate period before rolling them out to public clients. You can save yourself some painful iterations in public if you instead let additions cook for a while internally first.

**Comment by wincent** [comment]
I should add, the concrete example that I gave of `dob` was a bit contrived: if you were really going to do that you would probably just keep `birthday` as non-null and make sure that you always shipped at least and empty string (I just wanted to give an example of adding a new field rather than changing an existing one).

**Comment by raderio** [comment]
Thanks.
