### ISSUE TITLE
Specification on error responses

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#340]
Is there a specification about error responses, what status should be, what fields it should contains?

graphql-js respond with status 400 on invalid query
Github https://developer.github.com/v4/explorer/ respond with status 200 on invalid query

**Comment by wincent** [comment]
Thanks for the question, @raderio. The spec is intentionally silent on the subject of how requests and responses should be serialized and transported, because it is intended to concern itself only with the lower-level matters of how to parse, validate, execute, introspect GraphQL queries. As the readme says, this in order:

>  ... to be broadly adopted ... GraphQL will have to target a wide variety of backends, frameworks, and languages ...

You'll find only the briefest of mentions of actual transport in the spec text, and non-normatively at that:

> ... values of which are often serialized when sent over a transport like HTTP ... not all platforms and transports support encoding integer numbers larger than 32-bit ... etc ...

You say:

> graphql-js respond with status 400 on invalid query

graphql-js has no notion of HTTP at all. Perhaps you are referring to express-graphql? In express-graphql, we elect to deal with invalid queries using a 400 status code, because codes in the 400 range are intended to indicate client errors, and supplying an invalid query is a client error.
