### ISSUE TITLE
Filters: less than, greater than

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#341]
```
type Person {
    firstName: String!,
    lastName: String!,
    age: Int!
}
```

How to query all people what are older than 18?

**Comment by stubailo** [comment]
That's not part of the graphql specification - you need to add arguments to your fields for all of the filters you would like to support.

**Comment by wincent** [comment]
Thanks for the question @raderio (and the answer, @stubailo).

@raderio, if you hit Stack Overflow and search for "graphql filter" you'll see some questions/answers with examples of how to filter (and paginate). Just say you end up exposing your results under a `people` field, you may end up setting up arguments for it like `people(minAge: 18)`, and if you require pagination, `people(first: 10, minAge: 18)` etc. Those are just examples, because there are plenty of valid ways to do this. Like @stubailo said, the specification is (intentionally) silent on schema design patterns, so I'd suggest you look around at the prior art out there in order to guide you.

**Comment by idibidiart** [comment]
To clarify the answer, you would pass the arguments to yoir resolvers and deal with it at the API or db query level, wherever you're getting your data from.
