### ISSUE TITLE
Proposal: field / argument Absent-or-non-null

### ISSUE THREAD

**Issue by axos88** [facebook/graphql#408]
Currently there is no way to express that an input field / argument must be either absent ( not specified), or non null.
This would come particularly handy in update mutations in case of mandatory data, where absence means not touching the particular data field, but if it is present, it must be non null.

What do you think?

**Comment by gkesler** [comment]
Could the same be achieved using directive, like `@sparse(if: true)` to specify that the mutation should be handled by persisting *only* specified input fields vs. `@sparse(if: false)` that means persisting *all* fields and combination of validation constraints that anyways need to exist on the receiving side? 

It looks to me this **Absent-or-non-null** type is a kind of the constraint on the input field. Then the next question is what to do with other popular constraints: **pattern**, **min value**, **max value**, **min size**, **max size**, etc.?

**Comment by leebyron** [comment]
To keep things simple, Non-Null types require a value to be both present and non-null. The thinking was that there was no realistic scenario where absent or non-null (or required but nullable) was useful since the cases we could come up with could still be modeled (though with some slight awkwardness) with the single dimension. 

Some examples:

The most common desire for *either absent or non-null* is for optional data that, if-specified, must be a non null value. A normal nullable type allows for absence, which is half the desired use case - but allows the explicit value `null`. However now the backing service gets to decide how to handle that. It's three options are:

1. Use an explicit `null` value in whatever computation expected an optional non-null value. Let's hope it does not choose this one.
2. Throw an error. Ideally GraphQL validation ideally would have caught this earlier, but throwing an error could be reasonable.
3. Treat it as if it were not provided. In other words in this scenario `null` is isomorphic to having not provided a value. This is how GraphQL worked before introducing literal `null` values and may still be a reasonable option if it models intent.

The other unsupported combination is *required and nullable* which is sometimes desired for cases where we want a request to be explicit about a choice, even if it's request was `null`. If this is an enum, introduce an explicit enum value for this explicit choice. If another type, or if `null` is truly a value to be included then use a nullable type with an option to throw an error if not explicitly provided.

---

The use cases desired can still be met, even though there are some caveats. However the goal in designing the GraphQL language is not to support every use case without caveats - it is to carefully balance expressiveness with complexity. In this particular case it was decided that the additional complexity to model these two use cases was not worth the increase in expressiveness.

Hope that helps answer questions and provide a path forward
