### ISSUE TITLE
Syntax to format k-v pairs to table

### ISSUE THREAD

**Issue by BigYu** [facebook/graphql#416]
For example we have a structure like this:

```
user {
    id,
    name,
}
```

In case we may want to fetch the data of lots of users in a call, we will get response like this:

```
{
  "data": [
    {"id": "some_id", "name": "some_name"},
    // ...more records
   ]
}
```

Any recommendation if I want to format the response in this pattern to reduce the redundant keys in response body?

```
{
  "data": {
    "headers": ["id", "name"],
    "body": [["some_id", "some_name"], ["another_id", "another_name"], //....] // 2-dimension array without redundant keys. No need to repeat the strings "id", "name" for hundreds of times.
  }
}
```

**Comment by leebyron** [comment]
I highly recommend gzipping your json response bodies since nearly every networking client has some gzip inflating behavior baked in. It also performs unreasonably well for both bytes-on-wire and client CPU. 

I've seen plenty of creative experiments with response serialization and none so far have beat gzipped json on balance for both network bytes and client CPU.

However I'll just remind you that [GraphQL does not require a specific serialization format](http://facebook.github.io/graphql/October2016/#sec-Serialization-Format). By no means are you limited to JSON if you want to experiment with something new - as long as clients of your GraphQL service know how to deserialize the result.
