### ISSUE TITLE
[question] why names cannot contain dash '-'

### ISSUE THREAD

**Issue by liweinan0423** [facebook/graphql#479]
currently the name only supports `/[_A-Za-z][_0-9A-Za-z]*/`

**Comment by IvanGoncharov** [comment]
@liweinan0423 Because `A-Za-z0-9_` is the only characters that supported in all environments.
For example, the majority of programming languages don't support `-` inside property names so it will make code/typings generation harder.

**Comment by jlouis** [comment]
And to add more background information:

The - character tends to interfere with parsing of a name such as `x-y`. Is this now an identifier `x-y` or is it a subtraction: `SUB x y` in an AST node? In most languages, this is ambiguous and thus, the `-` character is often disallowed in identifier names. Even if GraphQL doesn't use `-`, languages in which it is embedded often do.

An important exception to the rule are Lisp-like languages (Common Lisp, Scheme, Racket, Clojure) where the notation is an s-expression `(- x y)` in the above case. Since everything is coded as a prefix it is clear one can use names with a dash in those languages, and it is seen quite often on those languages. E.g. `(string-append "hello" "world" "!")`.

Likewise, catenative languages are likely to accept a `-` in other positions as well.

**Comment by liweinan0423** [comment]
@IvanGoncharov @jlouis Thanks very much for the explanation. 

I asked this questions because I am developing a GraphQL schema where there is something like 
```
address {
  "en-GB": "Address in English",
 "zh-CN": "Address in Simplified Chinese",
  "zh-HK": "Address in Traditional Chinese"
}
```

Maybe I have to change to another approach.

**Comment by IvanGoncharov** [comment]
@liweinan0423 Using dash definitely makes sense for locale names but off the top of my head I can't come up with any other domain where the dash is an essential part of terminology.
At the same time it's very easy to give an example of some other domain where other symbols are essential, e.g. MIME types as field name also make sense:
```
data {
  "application/json": "data in JSON format",
  "application/xml":  "data in XML format
}
```
So real question here should we support bigger subset of ASCII range or not?

And I personally think it's not worth added complexity and we should stick with biggest common denominator in form of `/[_A-Za-z][_0-9A-Za-z]*/`.

**Comment by OlegIlyenko** [comment]
@liweinan0423 we had exactly the same challenge for localized strings in out API. Since the set of available locales is dynamic and changes over time, we decided not to bake such fields as `en` or `en-GB` into the GraphQL schema (and in general I would advise not to do so).

We ended up providing 2 GraphQL fields for every localized property (for 2 different use-cases our clients have):

```graphql
type LocalizedString {
  locale: String
  value: String
}

type User {
  address(locale: String, fallbackLocales: [String]): LocalizedString
  addressAllLocales: [LocalizedString!]
}
```

`address` field is designed for user-facing apps that normally work with a single locale (user language). `addressAllLocales` is designed for admin-style applications that normally present localized strings in all locales and allow users to view and edit them.

Not sure whether this approach will work for you, but I hope it helps :)

**Comment by IvanGoncharov** [comment]
@liweinan0423 Can I close this issue?

**Comment by liweinan0423** [comment]
@IvanGoncharov sure, thanks very much for your clarification.

**Comment by stanislav-sidorov** [comment]
hi there, i have the MySQL database with fields that include hyphen, is the any chance to query from 'name-en-EN'? thanks

**Comment by sungam3r** [comment]
GraphQL has nothing to do with databases, GraphQL knows nothing about them. If you use some library to automatically translate graphql request into sql request text, then this is a matter of configure this library.

**Comment by stanislav-sidorov** [comment]
yes, you're right, i'm using knex js, here is a part of code to get all products from mySQL database.
```
all: (req, res) => {
        connection.query('SELECT * FROM products', async (err, rows) => {
            if (!err) {
                const response = await graphql(productsSchema, productsQuery, {products: rows});
                res.setHeader('Content-Type', 'application/json');
                res.status(200).send(JSON.stringify(
                    {
                        'result' : 'success',
                        'data': response.data
                    })
                );
            } else {
                res.status(400).send(err);
            }
        });
    },
```

and here is a graphql schema and a query to get specific fields

```
productsSchema: buildSchema(`
        type Product {
            product_id: ID
            name_ru-RU: String
            product_price: Float
        }
        type Query {
          products(id: ID): [Product]
        }`
      ),
      productsQuery: `
        {
          products {
            product_id
            name_ru-RU
            product_price
          }
        }`
      }
```
what you mean by configuring the library in my case?

**Comment by sungam3r** [comment]
You can configure sql text itself using MySql field alias for fields like `my-field`: `select my-field as my_field`. You choose the replacement method yourself. Then the schema may have acceptable field names.

**Comment by stanislav-sidorov** [comment]
thank you a lot, changed ```"SELECT * FROM products"``` to ```SELECT `name_ru-RU` as name, product_id, product_price FROM products```
