### ISSUE TITLE
Allow directives on directive definitions

### ISSUE THREAD

**Issue by benhead** [facebook/graphql#566]
We'd like to be able to declare directives on directive definitions.

We have tooling that uses type system directives to perform special processing on a schema, and we'd like users of that tooling to be able to define their own directives, with metadata indicating to the tooling that this directive is for its use. For example, if we could define `directive @Handler(class:String!) on DIRECTIVE_DEFINITION` then our users could define `directive @CustomDirective(...) on FIELD_DEFINITION @Handler(class:"Foo")` telling our tooling that their directive is meant to be handled by it, passing arguments we declare to our tooling, and still providing whatever arguments they declare to their own hooks.

That directives can't be declared on directive definitions seems like an oversight.

**Comment by IvanGoncharov** [comment]
@benhead Thanks for describing this proposal and especially for the PR.
I think having #567 is enough to track this proposal.
I'm closing this one since it's better to have entire disscussion in one place.

@benhead Can you please edit your initial comment in #567 to include detail description from this issue?
