### ISSUE TITLE
Should I have multiple GraphQL instances or just a single one?

### ISSUE THREAD

**Issue by rdsedmundo** [facebook/graphql#569]
https://stackoverflow.com/questions/54676109/should-i-have-multiple-graphql-instances-or-just-a-single-one

By any chance, someone from the Facebook / GraphQL team could answer this question?

I believe it's a common question that a lot of different teams come across it at some point. The documentation mentions "single endpoint", but it doesn't elaborate until when this is still valid. This could be even included there on a FAQ perhaps.

Try searching by something similar on Google and you'll see that there are no answers for that, and while this question is fairly new, it's already appearing on the top of the results.

cc @leebyron @IvanGoncharov @mjmahone @AGS- @jspahrsummers

**Comment by IvanGoncharov** [comment]
@rdsedmundo 
Disclaimer: I'm not FB employee.
AFAIK FB has one huge GraphQL Schema with 10k+ types:
https://github.com/facebook/graphql/issues/163#issuecomment-271367691
Here is also talk on the topic from one of the GraphQL authors:
https://www.youtube.com/watch?v=zMa8rfXI6MM

> This could be even included there on a FAQ perhaps.

I think we need to focus more on technical side of GraphQL and allow community to figure out the best architectural patterns for different domains and platforms.
So I'm closing this issue since it's outside of scope for this repo.

P.S.
> we're afraid of turning the original GraphQL layer on a monolith that would behave as a single point of failure in case of a disaster, for instance.

My personal opinion is that stateless GraphQL gateway is not a single point of failure since you can reset it or scale to more machines.

**Comment by jlouis** [comment]
As another data point, I'd recommend trying to keep a single namespace for as long as possible. The advantage is that it is far easier to transport data from one domain to another, and it also maximizes the ability to use interfaces and unions.

There may be good reasons to have a "split horizon" style where you have a public facing world and an internal world which is the public facing world + extra fields on certain endpoints. GraphQL extensions is an obvious candidate for such a solution. OTOH, just keep it all in one namespace makes your own internal systems into standard consumers. If you can handle this through authentication/authorization, then there are many alluring reasons to do so.

As for the SPOF, I'm agreeing with Ivan: Your GraphQL service should:

* Be running on multiple instances. This provides for easier redundancy and also simplifies rolling upgrades a lot: provide new functionality, roll it out and then enable it in clients.
* Be a factoring point. When a request factors through the graph, the underlying system is flexible and amenable to change without the clients knowing.
* Be a messaging hub. Collect subsystems in one graph, but serve those systems with multiple services. As an example, at $work, we use ElasticSearch for general search of objects in the Graph, but then use usual cached DB access to materialize data from those searches.
* Be a concurrency runner for clients. When a client poses a request, the request can be run concurrently for different parts of it. This allows parallelism. The GraphQL server is the point which proxies the concurrency of the client on the server side in order to make a low-latency request available. At $work, we use Erlang for this, so an Erlang process is the "client by proxy" in our system. But that proxy talks to other backend systems in order to carry out its work.
* Be able to do partial answers: If one service is down, you can still partially answer for the rest of the query. GraphQL is very explicit about `null`-propagation because this allows a client to work with partial requests in which certain parts of the request has failed to complete. This helps robustness.

**Comment by leebyron** [comment]
> I believe it's a common question that a lot of different teams come across it at some point. The documentation mentions "single endpoint", but it doesn't elaborate until when this is still valid.

The most simple way I think about when it's time to create a new endpoint is when you have a new independent "graph". If you find that you have a whole new collection of types that don't really relate to your existing types and are unlikely to ever in the future, then a new endpoint with a new graphql schema is appropriate.

A good example of this might be if you've company is centered around a product and has built a graphql API for that product, and then decides to expand into a new business domain with a new product that doesn't relate to the original product. It could be a burden for both of these unrelated products to share a single API and two separate endpoints with different schema may be more appropriate.

Admittedly this is a pretty rare scenario. Keeping your graph unified is pretty high value in nearly all cases.

Another example is what @jlouis suggested - you may have a separate internal-only endpoint that is a *superset* of your external GraphQL API. Facebook uses this pattern and has *two* endpoints, one internal and one external. The internal one includes internal tools which can interact with product types.
