### ISSUE TITLE
Drop colon (:) for type definitions and $ from query variable

### ISSUE THREAD

**Issue by tristanz** [facebook/graphql#69]
This is a totally stylistic, bikeshedding comment...  but maybe worth considering if I'm not missing something obvious.

It seems like both the informal schema format and query variables could be simplified by eliminating the colon from type definitions and dollar sign from variables. Right now the colon is used in so many different contexts (variables, types, interfaces, aliases).  The similarity between type definitions and passing arguments in particular is mildly confusing.

Why not change :

```
type Person : NamedEntity {
  name: String
  gravatar(height: Int, width: Int): Gravatar
}
```

to 

```
type Person : NamedEntity {
  name String
  gravatar(height Int, width Int) Gravatar
}
```

The same with queries.  Why not change:

```
query myQuery($someTest: Boolean, $size: Boolean) {
  gravatar(size: $size)
  experimentalField @include(if: $someTest)
}
```

to 

```
query myQuery($someTest Boolean, $size Boolean) {
  gravatar(size: $size)
  experimentalField @include(if: $someTest)
}
```

so that outer type definitions and inner arguments don't look so similar.

Finally, is the dollar sign really required?  Why not just:

```
query myQuery(someTest Boolean, size Boolean) {
  gravatar(size: size)
  experimentalField @include(if: someTest)
}
```

**Comment by leebyron** [comment]
Thanks for this feedback. This is a lot, so let me try to address each point.

For colons in the type definition field arguments and variable definitions, we're hoping to do two things:

1. Create a visual mirroring between the definition of the field arguments and the usage of them.
2. More importantly, leverage existing knowledge of other languages where syntax works this way: Flow, TypeScript, Swift, amidst others.

>  is the dollar sign really required? 

Yes, it syntactically avoids an ambiguity between a possible enum values and variables.

```
enum Color {
  red
  green
  blue
}

query coloredThing($color: Color) {
  variableThing: thing(color: $color)
  redThing: thing(color: red)
}
```

Also, variables have a different frequency and importance in a query language than they do in a programming language. When using a programming language, variables are often the most common token you use, so keeping them unadorned is important for legibility. In query languages, however, variables are fairly rare relative to data description identifiers. When variables are used, it's important to visually highlight them so that it's clear. We use the `$` sigil as a way to visually identify variables.

**Comment by tristanz** [comment]
Makes sense, thanks.
